name: Train ML Model (Notebook)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies and register kernel
      run: |
        pip install -r requirements.txt
        pip install notebook nbconvert ipykernel
        python -m ipykernel install --user --name python3


    - name: Run training notebook
      run: |
        jupyter nbconvert --to notebook --execute train.ipynb

    - name: Write Job Summary
      run: |
        echo "## ML Experiment Results" >> $GITHUB_STEP_SUMMARY
        echo "**Name:** Kaustubh Bhalerao" >> $GITHUB_STEP_SUMMARY
        echo "**Roll No:** 2022BCS0172" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        cat outputs/results/metrics.json >> $GITHUB_STEP_SUMMARY

    - name: Upload trained model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: outputs/model/

    - name: Upload metrics
      uses: actions/upload-artifact@v4
      with:
        name: evaluation-results
        path: outputs/results/
